CREATE TYPE mood AS ENUM ('Trainee', 'Junior', 'Middle', 'Senior');

CREATE TABLE worker (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
    LEVEL mood NOT NULL,
    SALARY INTEGER CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000)
);

CREATE TABLE project (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER NOT NULL,
    START_DATE DATE,
    FINISH_DATE DATE,
    CONSTRAINT FK_Client_ID FOREIGN KEY (CLIENT_ID) REFERENCES client(ID) ON DELETE CASCADE
);
CREATE TABLE project_worker (
    PROJECT_ID BIGINT,
    WORKER_ID BIGINT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID) ON DELETE CASCADE
);